package com.google.android.gms.internal.mlkit_common;

import com.pichillilorenzo.flutter_inappwebview_android.R;
import ga.c;
import ga.d;
import ga.e;

/* JADX INFO: loaded from: classes.dex */
final class zzha implements d {
    private static final c zzA;
    private static final c zzB;
    private static final c zzC;
    private static final c zzD;
    private static final c zzE;
    private static final c zzF;
    private static final c zzG;
    private static final c zzH;
    private static final c zzI;
    private static final c zzJ;
    private static final c zzK;
    private static final c zzL;
    private static final c zzM;
    private static final c zzN;
    private static final c zzO;
    private static final c zzP;
    private static final c zzQ;
    private static final c zzR;
    private static final c zzS;
    private static final c zzT;
    private static final c zzU;
    private static final c zzV;
    private static final c zzW;
    private static final c zzX;
    private static final c zzY;
    private static final c zzZ;
    static final zzha zza = new zzha();
    private static final c zzaA;
    private static final c zzaB;
    private static final c zzaC;
    private static final c zzaD;
    private static final c zzaE;
    private static final c zzaF;
    private static final c zzaG;
    private static final c zzaH;
    private static final c zzaI;
    private static final c zzaJ;
    private static final c zzaK;
    private static final c zzaL;
    private static final c zzaM;
    private static final c zzaN;
    private static final c zzaO;
    private static final c zzaP;
    private static final c zzaQ;
    private static final c zzaR;
    private static final c zzaS;
    private static final c zzaT;
    private static final c zzaU;
    private static final c zzaV;
    private static final c zzaW;
    private static final c zzaX;
    private static final c zzaY;
    private static final c zzaZ;
    private static final c zzaa;
    private static final c zzab;
    private static final c zzac;
    private static final c zzad;
    private static final c zzae;
    private static final c zzaf;
    private static final c zzag;
    private static final c zzah;
    private static final c zzai;
    private static final c zzaj;
    private static final c zzak;
    private static final c zzal;
    private static final c zzam;
    private static final c zzan;
    private static final c zzao;
    private static final c zzap;
    private static final c zzaq;
    private static final c zzar;
    private static final c zzas;
    private static final c zzat;
    private static final c zzau;
    private static final c zzav;
    private static final c zzaw;
    private static final c zzax;
    private static final c zzay;
    private static final c zzaz;
    private static final c zzb;
    private static final c zzba;
    private static final c zzbb;
    private static final c zzbc;
    private static final c zzbd;
    private static final c zzbe;
    private static final c zzbf;
    private static final c zzbg;
    private static final c zzbh;
    private static final c zzbi;
    private static final c zzbj;
    private static final c zzbk;
    private static final c zzbl;
    private static final c zzbm;
    private static final c zzbn;
    private static final c zzbo;
    private static final c zzbp;
    private static final c zzbq;
    private static final c zzbr;
    private static final c zzbs;
    private static final c zzbt;
    private static final c zzbu;
    private static final c zzbv;
    private static final c zzbw;
    private static final c zzbx;
    private static final c zzby;
    private static final c zzc;
    private static final c zzd;
    private static final c zze;
    private static final c zzf;
    private static final c zzg;
    private static final c zzh;
    private static final c zzi;
    private static final c zzj;
    private static final c zzk;
    private static final c zzl;
    private static final c zzm;
    private static final c zzn;
    private static final c zzo;
    private static final c zzp;
    private static final c zzq;
    private static final c zzr;
    private static final c zzs;
    private static final c zzt;
    private static final c zzu;
    private static final c zzv;
    private static final c zzw;
    private static final c zzx;
    private static final c zzy;
    private static final c zzz;

    static {
        c.b bVarA = c.a("systemInfo");
        zzbj zzbjVar = new zzbj();
        zzbjVar.zza(1);
        zzb = bVarA.b(zzbjVar.zzb()).a();
        c.b bVarA2 = c.a("eventName");
        zzbj zzbjVar2 = new zzbj();
        zzbjVar2.zza(2);
        zzc = bVarA2.b(zzbjVar2.zzb()).a();
        c.b bVarA3 = c.a("isThickClient");
        zzbj zzbjVar3 = new zzbj();
        zzbjVar3.zza(37);
        zzd = bVarA3.b(zzbjVar3.zzb()).a();
        c.b bVarA4 = c.a("clientType");
        zzbj zzbjVar4 = new zzbj();
        zzbjVar4.zza(61);
        zze = bVarA4.b(zzbjVar4.zzb()).a();
        c.b bVarA5 = c.a("modelDownloadLogEvent");
        zzbj zzbjVar5 = new zzbj();
        zzbjVar5.zza(3);
        zzf = bVarA5.b(zzbjVar5.zzb()).a();
        c.b bVarA6 = c.a("customModelLoadLogEvent");
        zzbj zzbjVar6 = new zzbj();
        zzbjVar6.zza(20);
        zzg = bVarA6.b(zzbjVar6.zzb()).a();
        c.b bVarA7 = c.a("customModelInferenceLogEvent");
        zzbj zzbjVar7 = new zzbj();
        zzbjVar7.zza(4);
        zzh = bVarA7.b(zzbjVar7.zzb()).a();
        c.b bVarA8 = c.a("customModelCreateLogEvent");
        zzbj zzbjVar8 = new zzbj();
        zzbjVar8.zza(29);
        zzi = bVarA8.b(zzbjVar8.zzb()).a();
        c.b bVarA9 = c.a("onDeviceFaceDetectionLogEvent");
        zzbj zzbjVar9 = new zzbj();
        zzbjVar9.zza(5);
        zzj = bVarA9.b(zzbjVar9.zzb()).a();
        c.b bVarA10 = c.a("onDeviceFaceLoadLogEvent");
        zzbj zzbjVar10 = new zzbj();
        zzbjVar10.zza(59);
        zzk = bVarA10.b(zzbjVar10.zzb()).a();
        c.b bVarA11 = c.a("onDeviceTextDetectionLogEvent");
        zzbj zzbjVar11 = new zzbj();
        zzbjVar11.zza(6);
        zzl = bVarA11.b(zzbjVar11.zzb()).a();
        c.b bVarA12 = c.a("onDeviceTextDetectionLoadLogEvent");
        zzbj zzbjVar12 = new zzbj();
        zzbjVar12.zza(79);
        zzm = bVarA12.b(zzbjVar12.zzb()).a();
        c.b bVarA13 = c.a("onDeviceBarcodeDetectionLogEvent");
        zzbj zzbjVar13 = new zzbj();
        zzbjVar13.zza(7);
        zzn = bVarA13.b(zzbjVar13.zzb()).a();
        c.b bVarA14 = c.a("onDeviceBarcodeLoadLogEvent");
        zzbj zzbjVar14 = new zzbj();
        zzbjVar14.zza(58);
        zzo = bVarA14.b(zzbjVar14.zzb()).a();
        c.b bVarA15 = c.a("onDeviceImageLabelCreateLogEvent");
        zzbj zzbjVar15 = new zzbj();
        zzbjVar15.zza(48);
        zzp = bVarA15.b(zzbjVar15.zzb()).a();
        c.b bVarA16 = c.a("onDeviceImageLabelLoadLogEvent");
        zzbj zzbjVar16 = new zzbj();
        zzbjVar16.zza(49);
        zzq = bVarA16.b(zzbjVar16.zzb()).a();
        c.b bVarA17 = c.a("onDeviceImageLabelDetectionLogEvent");
        zzbj zzbjVar17 = new zzbj();
        zzbjVar17.zza(18);
        zzr = bVarA17.b(zzbjVar17.zzb()).a();
        c.b bVarA18 = c.a("onDeviceObjectCreateLogEvent");
        zzbj zzbjVar18 = new zzbj();
        zzbjVar18.zza(26);
        zzs = bVarA18.b(zzbjVar18.zzb()).a();
        c.b bVarA19 = c.a("onDeviceObjectLoadLogEvent");
        zzbj zzbjVar19 = new zzbj();
        zzbjVar19.zza(27);
        zzt = bVarA19.b(zzbjVar19.zzb()).a();
        c.b bVarA20 = c.a("onDeviceObjectInferenceLogEvent");
        zzbj zzbjVar20 = new zzbj();
        zzbjVar20.zza(28);
        zzu = bVarA20.b(zzbjVar20.zzb()).a();
        c.b bVarA21 = c.a("onDevicePoseDetectionLogEvent");
        zzbj zzbjVar21 = new zzbj();
        zzbjVar21.zza(44);
        zzv = bVarA21.b(zzbjVar21.zzb()).a();
        c.b bVarA22 = c.a("onDeviceSegmentationLogEvent");
        zzbj zzbjVar22 = new zzbj();
        zzbjVar22.zza(45);
        zzw = bVarA22.b(zzbjVar22.zzb()).a();
        c.b bVarA23 = c.a("onDeviceSmartReplyLogEvent");
        zzbj zzbjVar23 = new zzbj();
        zzbjVar23.zza(19);
        zzx = bVarA23.b(zzbjVar23.zzb()).a();
        c.b bVarA24 = c.a("onDeviceLanguageIdentificationLogEvent");
        zzbj zzbjVar24 = new zzbj();
        zzbjVar24.zza(21);
        zzy = bVarA24.b(zzbjVar24.zzb()).a();
        c.b bVarA25 = c.a("onDeviceTranslationLogEvent");
        zzbj zzbjVar25 = new zzbj();
        zzbjVar25.zza(22);
        zzz = bVarA25.b(zzbjVar25.zzb()).a();
        c.b bVarA26 = c.a("cloudFaceDetectionLogEvent");
        zzbj zzbjVar26 = new zzbj();
        zzbjVar26.zza(8);
        zzA = bVarA26.b(zzbjVar26.zzb()).a();
        c.b bVarA27 = c.a("cloudCropHintDetectionLogEvent");
        zzbj zzbjVar27 = new zzbj();
        zzbjVar27.zza(9);
        zzB = bVarA27.b(zzbjVar27.zzb()).a();
        c.b bVarA28 = c.a("cloudDocumentTextDetectionLogEvent");
        zzbj zzbjVar28 = new zzbj();
        zzbjVar28.zza(10);
        zzC = bVarA28.b(zzbjVar28.zzb()).a();
        c.b bVarA29 = c.a("cloudImagePropertiesDetectionLogEvent");
        zzbj zzbjVar29 = new zzbj();
        zzbjVar29.zza(11);
        zzD = bVarA29.b(zzbjVar29.zzb()).a();
        c.b bVarA30 = c.a("cloudImageLabelDetectionLogEvent");
        zzbj zzbjVar30 = new zzbj();
        zzbjVar30.zza(12);
        zzE = bVarA30.b(zzbjVar30.zzb()).a();
        c.b bVarA31 = c.a("cloudLandmarkDetectionLogEvent");
        zzbj zzbjVar31 = new zzbj();
        zzbjVar31.zza(13);
        zzF = bVarA31.b(zzbjVar31.zzb()).a();
        c.b bVarA32 = c.a("cloudLogoDetectionLogEvent");
        zzbj zzbjVar32 = new zzbj();
        zzbjVar32.zza(14);
        zzG = bVarA32.b(zzbjVar32.zzb()).a();
        c.b bVarA33 = c.a("cloudSafeSearchDetectionLogEvent");
        zzbj zzbjVar33 = new zzbj();
        zzbjVar33.zza(15);
        zzH = bVarA33.b(zzbjVar33.zzb()).a();
        c.b bVarA34 = c.a("cloudTextDetectionLogEvent");
        zzbj zzbjVar34 = new zzbj();
        zzbjVar34.zza(16);
        zzI = bVarA34.b(zzbjVar34.zzb()).a();
        c.b bVarA35 = c.a("cloudWebSearchDetectionLogEvent");
        zzbj zzbjVar35 = new zzbj();
        zzbjVar35.zza(17);
        zzJ = bVarA35.b(zzbjVar35.zzb()).a();
        c.b bVarA36 = c.a("automlImageLabelingCreateLogEvent");
        zzbj zzbjVar36 = new zzbj();
        zzbjVar36.zza(23);
        zzK = bVarA36.b(zzbjVar36.zzb()).a();
        c.b bVarA37 = c.a("automlImageLabelingLoadLogEvent");
        zzbj zzbjVar37 = new zzbj();
        zzbjVar37.zza(24);
        zzL = bVarA37.b(zzbjVar37.zzb()).a();
        c.b bVarA38 = c.a("automlImageLabelingInferenceLogEvent");
        zzbj zzbjVar38 = new zzbj();
        zzbjVar38.zza(25);
        zzM = bVarA38.b(zzbjVar38.zzb()).a();
        c.b bVarA39 = c.a("isModelDownloadedLogEvent");
        zzbj zzbjVar39 = new zzbj();
        zzbjVar39.zza(39);
        zzN = bVarA39.b(zzbjVar39.zzb()).a();
        c.b bVarA40 = c.a("deleteModelLogEvent");
        zzbj zzbjVar40 = new zzbj();
        zzbjVar40.zza(40);
        zzO = bVarA40.b(zzbjVar40.zzb()).a();
        c.b bVarA41 = c.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzbj zzbjVar41 = new zzbj();
        zzbjVar41.zza(30);
        zzP = bVarA41.b(zzbjVar41.zzb()).a();
        c.b bVarA42 = c.a("aggregatedCustomModelInferenceLogEvent");
        zzbj zzbjVar42 = new zzbj();
        zzbjVar42.zza(31);
        zzQ = bVarA42.b(zzbjVar42.zzb()).a();
        c.b bVarA43 = c.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzbj zzbjVar43 = new zzbj();
        zzbjVar43.zza(32);
        zzR = bVarA43.b(zzbjVar43.zzb()).a();
        c.b bVarA44 = c.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzbj zzbjVar44 = new zzbj();
        zzbjVar44.zza(33);
        zzS = bVarA44.b(zzbjVar44.zzb()).a();
        c.b bVarA45 = c.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzbj zzbjVar45 = new zzbj();
        zzbjVar45.zza(34);
        zzT = bVarA45.b(zzbjVar45.zzb()).a();
        c.b bVarA46 = c.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzbj zzbjVar46 = new zzbj();
        zzbjVar46.zza(35);
        zzU = bVarA46.b(zzbjVar46.zzb()).a();
        c.b bVarA47 = c.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzbj zzbjVar47 = new zzbj();
        zzbjVar47.zza(36);
        zzV = bVarA47.b(zzbjVar47.zzb()).a();
        c.b bVarA48 = c.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzbj zzbjVar48 = new zzbj();
        zzbjVar48.zza(46);
        zzW = bVarA48.b(zzbjVar48.zzb()).a();
        c.b bVarA49 = c.a("aggregatedOnDeviceSegmentationLogEvent");
        zzbj zzbjVar49 = new zzbj();
        zzbjVar49.zza(47);
        zzX = bVarA49.b(zzbjVar49.zzb()).a();
        c.b bVarA50 = c.a("pipelineAccelerationInferenceEvents");
        zzbj zzbjVar50 = new zzbj();
        zzbjVar50.zza(69);
        zzY = bVarA50.b(zzbjVar50.zzb()).a();
        c.b bVarA51 = c.a("remoteConfigLogEvent");
        zzbj zzbjVar51 = new zzbj();
        zzbjVar51.zza(42);
        zzZ = bVarA51.b(zzbjVar51.zzb()).a();
        c.b bVarA52 = c.a("inputImageConstructionLogEvent");
        zzbj zzbjVar52 = new zzbj();
        zzbjVar52.zza(50);
        zzaa = bVarA52.b(zzbjVar52.zzb()).a();
        c.b bVarA53 = c.a("leakedHandleEvent");
        zzbj zzbjVar53 = new zzbj();
        zzbjVar53.zza(51);
        zzab = bVarA53.b(zzbjVar53.zzb()).a();
        c.b bVarA54 = c.a("cameraSourceLogEvent");
        zzbj zzbjVar54 = new zzbj();
        zzbjVar54.zza(52);
        zzac = bVarA54.b(zzbjVar54.zzb()).a();
        c.b bVarA55 = c.a("imageLabelOptionalModuleLogEvent");
        zzbj zzbjVar55 = new zzbj();
        zzbjVar55.zza(53);
        zzad = bVarA55.b(zzbjVar55.zzb()).a();
        c.b bVarA56 = c.a("languageIdentificationOptionalModuleLogEvent");
        zzbj zzbjVar56 = new zzbj();
        zzbjVar56.zza(54);
        zzae = bVarA56.b(zzbjVar56.zzb()).a();
        c.b bVarA57 = c.a("faceDetectionOptionalModuleLogEvent");
        zzbj zzbjVar57 = new zzbj();
        zzbjVar57.zza(60);
        zzaf = bVarA57.b(zzbjVar57.zzb()).a();
        c.b bVarA58 = c.a("documentDetectionOptionalModuleLogEvent");
        zzbj zzbjVar58 = new zzbj();
        zzbjVar58.zza(85);
        zzag = bVarA58.b(zzbjVar58.zzb()).a();
        c.b bVarA59 = c.a("documentCroppingOptionalModuleLogEvent");
        zzbj zzbjVar59 = new zzbj();
        zzbjVar59.zza(86);
        zzah = bVarA59.b(zzbjVar59.zzb()).a();
        c.b bVarA60 = c.a("documentEnhancementOptionalModuleLogEvent");
        zzbj zzbjVar60 = new zzbj();
        zzbjVar60.zza(87);
        zzai = bVarA60.b(zzbjVar60.zzb()).a();
        c.b bVarA61 = c.a("nlClassifierOptionalModuleLogEvent");
        zzbj zzbjVar61 = new zzbj();
        zzbjVar61.zza(55);
        zzaj = bVarA61.b(zzbjVar61.zzb()).a();
        c.b bVarA62 = c.a("nlClassifierClientLibraryLogEvent");
        zzbj zzbjVar62 = new zzbj();
        zzbjVar62.zza(56);
        zzak = bVarA62.b(zzbjVar62.zzb()).a();
        c.b bVarA63 = c.a("accelerationAllowlistLogEvent");
        zzbj zzbjVar63 = new zzbj();
        zzbjVar63.zza(57);
        zzal = bVarA63.b(zzbjVar63.zzb()).a();
        c.b bVarA64 = c.a("toxicityDetectionCreateEvent");
        zzbj zzbjVar64 = new zzbj();
        zzbjVar64.zza(62);
        zzam = bVarA64.b(zzbjVar64.zzb()).a();
        c.b bVarA65 = c.a("toxicityDetectionLoadEvent");
        zzbj zzbjVar65 = new zzbj();
        zzbjVar65.zza(63);
        zzan = bVarA65.b(zzbjVar65.zzb()).a();
        c.b bVarA66 = c.a("toxicityDetectionInferenceEvent");
        zzbj zzbjVar66 = new zzbj();
        zzbjVar66.zza(64);
        zzao = bVarA66.b(zzbjVar66.zzb()).a();
        c.b bVarA67 = c.a("barcodeDetectionOptionalModuleLogEvent");
        zzbj zzbjVar67 = new zzbj();
        zzbjVar67.zza(65);
        zzap = bVarA67.b(zzbjVar67.zzb()).a();
        c.b bVarA68 = c.a("customImageLabelOptionalModuleLogEvent");
        zzbj zzbjVar68 = new zzbj();
        zzbjVar68.zza(66);
        zzaq = bVarA68.b(zzbjVar68.zzb()).a();
        c.b bVarA69 = c.a("codeScannerScanApiEvent");
        zzbj zzbjVar69 = new zzbj();
        zzbjVar69.zza(67);
        zzar = bVarA69.b(zzbjVar69.zzb()).a();
        c.b bVarA70 = c.a("codeScannerOptionalModuleEvent");
        zzbj zzbjVar70 = new zzbj();
        zzbjVar70.zza(68);
        zzas = bVarA70.b(zzbjVar70.zzb()).a();
        c.b bVarA71 = c.a("onDeviceExplicitContentCreateLogEvent");
        zzbj zzbjVar71 = new zzbj();
        zzbjVar71.zza(70);
        zzat = bVarA71.b(zzbjVar71.zzb()).a();
        c.b bVarA72 = c.a("onDeviceExplicitContentLoadLogEvent");
        zzbj zzbjVar72 = new zzbj();
        zzbjVar72.zza(71);
        zzau = bVarA72.b(zzbjVar72.zzb()).a();
        c.b bVarA73 = c.a("onDeviceExplicitContentInferenceLogEvent");
        zzbj zzbjVar73 = new zzbj();
        zzbjVar73.zza(72);
        zzav = bVarA73.b(zzbjVar73.zzb()).a();
        c.b bVarA74 = c.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzbj zzbjVar74 = new zzbj();
        zzbjVar74.zza(73);
        zzaw = bVarA74.b(zzbjVar74.zzb()).a();
        c.b bVarA75 = c.a("onDeviceFaceMeshCreateLogEvent");
        zzbj zzbjVar75 = new zzbj();
        zzbjVar75.zza(74);
        zzax = bVarA75.b(zzbjVar75.zzb()).a();
        c.b bVarA76 = c.a("onDeviceFaceMeshLoadLogEvent");
        zzbj zzbjVar76 = new zzbj();
        zzbjVar76.zza(75);
        zzay = bVarA76.b(zzbjVar76.zzb()).a();
        c.b bVarA77 = c.a("onDeviceFaceMeshLogEvent");
        zzbj zzbjVar77 = new zzbj();
        zzbjVar77.zza(76);
        zzaz = bVarA77.b(zzbjVar77.zzb()).a();
        c.b bVarA78 = c.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzbj zzbjVar78 = new zzbj();
        zzbjVar78.zza(77);
        zzaA = bVarA78.b(zzbjVar78.zzb()).a();
        c.b bVarA79 = c.a("smartReplyOptionalModuleLogEvent");
        zzbj zzbjVar79 = new zzbj();
        zzbjVar79.zza(78);
        zzaB = bVarA79.b(zzbjVar79.zzb()).a();
        c.b bVarA80 = c.a("textDetectionOptionalModuleLogEvent");
        zzbj zzbjVar80 = new zzbj();
        zzbjVar80.zza(80);
        zzaC = bVarA80.b(zzbjVar80.zzb()).a();
        c.b bVarA81 = c.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzbj zzbjVar81 = new zzbj();
        zzbjVar81.zza(81);
        zzaD = bVarA81.b(zzbjVar81.zzb()).a();
        c.b bVarA82 = c.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzbj zzbjVar82 = new zzbj();
        zzbjVar82.zza(82);
        zzaE = bVarA82.b(zzbjVar82.zzb()).a();
        c.b bVarA83 = c.a("onDeviceImageQualityAnalysisLogEvent");
        zzbj zzbjVar83 = new zzbj();
        zzbjVar83.zza(83);
        zzaF = bVarA83.b(zzbjVar83.zzb()).a();
        c.b bVarA84 = c.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzbj zzbjVar84 = new zzbj();
        zzbjVar84.zza(84);
        zzaG = bVarA84.b(zzbjVar84.zzb()).a();
        c.b bVarA85 = c.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzbj zzbjVar85 = new zzbj();
        zzbjVar85.zza(88);
        zzaH = bVarA85.b(zzbjVar85.zzb()).a();
        c.b bVarA86 = c.a("imageCaptioningOptionalModuleLogEvent");
        zzbj zzbjVar86 = new zzbj();
        zzbjVar86.zza(89);
        zzaI = bVarA86.b(zzbjVar86.zzb()).a();
        c.b bVarA87 = c.a("onDeviceImageCaptioningCreateLogEvent");
        zzbj zzbjVar87 = new zzbj();
        zzbjVar87.zza(90);
        zzaJ = bVarA87.b(zzbjVar87.zzb()).a();
        c.b bVarA88 = c.a("onDeviceImageCaptioningLoadLogEvent");
        zzbj zzbjVar88 = new zzbj();
        zzbjVar88.zza(91);
        zzaK = bVarA88.b(zzbjVar88.zzb()).a();
        c.b bVarA89 = c.a("onDeviceImageCaptioningInferenceLogEvent");
        zzbj zzbjVar89 = new zzbj();
        zzbjVar89.zza(92);
        zzaL = bVarA89.b(zzbjVar89.zzb()).a();
        c.b bVarA90 = c.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzbj zzbjVar90 = new zzbj();
        zzbjVar90.zza(93);
        zzaM = bVarA90.b(zzbjVar90.zzb()).a();
        c.b bVarA91 = c.a("onDeviceDocumentDetectionCreateLogEvent");
        zzbj zzbjVar91 = new zzbj();
        zzbjVar91.zza(94);
        zzaN = bVarA91.b(zzbjVar91.zzb()).a();
        c.b bVarA92 = c.a("onDeviceDocumentDetectionLoadLogEvent");
        zzbj zzbjVar92 = new zzbj();
        zzbjVar92.zza(95);
        zzaO = bVarA92.b(zzbjVar92.zzb()).a();
        c.b bVarA93 = c.a("onDeviceDocumentDetectionLogEvent");
        zzbj zzbjVar93 = new zzbj();
        zzbjVar93.zza(96);
        zzaP = bVarA93.b(zzbjVar93.zzb()).a();
        c.b bVarA94 = c.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzbj zzbjVar94 = new zzbj();
        zzbjVar94.zza(97);
        zzaQ = bVarA94.b(zzbjVar94.zzb()).a();
        c.b bVarA95 = c.a("onDeviceDocumentCroppingCreateLogEvent");
        zzbj zzbjVar95 = new zzbj();
        zzbjVar95.zza(98);
        zzaR = bVarA95.b(zzbjVar95.zzb()).a();
        c.b bVarA96 = c.a("onDeviceDocumentCroppingLoadLogEvent");
        zzbj zzbjVar96 = new zzbj();
        zzbjVar96.zza(99);
        zzaS = bVarA96.b(zzbjVar96.zzb()).a();
        c.b bVarA97 = c.a("onDeviceDocumentCroppingLogEvent");
        zzbj zzbjVar97 = new zzbj();
        zzbjVar97.zza(100);
        zzaT = bVarA97.b(zzbjVar97.zzb()).a();
        c.b bVarA98 = c.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzbj zzbjVar98 = new zzbj();
        zzbjVar98.zza(101);
        zzaU = bVarA98.b(zzbjVar98.zzb()).a();
        c.b bVarA99 = c.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzbj zzbjVar99 = new zzbj();
        zzbjVar99.zza(R.styleable.AppCompatTheme_textAppearanceLargePopupMenu);
        zzaV = bVarA99.b(zzbjVar99.zzb()).a();
        c.b bVarA100 = c.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzbj zzbjVar100 = new zzbj();
        zzbjVar100.zza(R.styleable.AppCompatTheme_textAppearanceListItem);
        zzaW = bVarA100.b(zzbjVar100.zzb()).a();
        c.b bVarA101 = c.a("onDeviceDocumentEnhancementLogEvent");
        zzbj zzbjVar101 = new zzbj();
        zzbjVar101.zza(R.styleable.AppCompatTheme_textAppearanceListItemSecondary);
        zzaX = bVarA101.b(zzbjVar101.zzb()).a();
        c.b bVarA102 = c.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzbj zzbjVar102 = new zzbj();
        zzbjVar102.zza(R.styleable.AppCompatTheme_textAppearanceListItemSmall);
        zzaY = bVarA102.b(zzbjVar102.zzb()).a();
        c.b bVarA103 = c.a("scannerAutoZoomEvent");
        zzbj zzbjVar103 = new zzbj();
        zzbjVar103.zza(R.styleable.AppCompatTheme_textAppearancePopupMenuHeader);
        zzaZ = bVarA103.b(zzbjVar103.zzb()).a();
        c.b bVarA104 = c.a("lowLightAutoExposureComputationEvent");
        zzbj zzbjVar104 = new zzbj();
        zzbjVar104.zza(R.styleable.AppCompatTheme_textAppearanceSearchResultSubtitle);
        zzba = bVarA104.b(zzbjVar104.zzb()).a();
        c.b bVarA105 = c.a("lowLightFrameProcessEvent");
        zzbj zzbjVar105 = new zzbj();
        zzbjVar105.zza(R.styleable.AppCompatTheme_textAppearanceSearchResultTitle);
        zzbb = bVarA105.b(zzbjVar105.zzb()).a();
        c.b bVarA106 = c.a("lowLightSceneDetectionEvent");
        zzbj zzbjVar106 = new zzbj();
        zzbjVar106.zza(R.styleable.AppCompatTheme_textAppearanceSmallPopupMenu);
        zzbc = bVarA106.b(zzbjVar106.zzb()).a();
        c.b bVarA107 = c.a("onDeviceStainRemovalLogEvent");
        zzbj zzbjVar107 = new zzbj();
        zzbjVar107.zza(R.styleable.AppCompatTheme_textColorAlertDialogListItem);
        zzbd = bVarA107.b(zzbjVar107.zzb()).a();
        c.b bVarA108 = c.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzbj zzbjVar108 = new zzbj();
        zzbjVar108.zza(R.styleable.AppCompatTheme_textColorSearchUrl);
        zzbe = bVarA108.b(zzbjVar108.zzb()).a();
        c.b bVarA109 = c.a("stainRemovalOptionalModuleLogEvent");
        zzbj zzbjVar109 = new zzbj();
        zzbjVar109.zza(R.styleable.AppCompatTheme_toolbarNavigationButtonStyle);
        zzbf = bVarA109.b(zzbjVar109.zzb()).a();
        c.b bVarA110 = c.a("onDeviceShadowRemovalLogEvent");
        zzbj zzbjVar110 = new zzbj();
        zzbjVar110.zza(R.styleable.AppCompatTheme_toolbarStyle);
        zzbg = bVarA110.b(zzbjVar110.zzb()).a();
        c.b bVarA111 = c.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzbj zzbjVar111 = new zzbj();
        zzbjVar111.zza(R.styleable.AppCompatTheme_tooltipForegroundColor);
        zzbh = bVarA111.b(zzbjVar111.zzb()).a();
        c.b bVarA112 = c.a("shadowRemovalOptionalModuleLogEvent");
        zzbj zzbjVar112 = new zzbj();
        zzbjVar112.zza(R.styleable.AppCompatTheme_tooltipFrameBackground);
        zzbi = bVarA112.b(zzbjVar112.zzb()).a();
        c.b bVarA113 = c.a("onDeviceDigitalInkSegmentationLogEvent");
        zzbj zzbjVar113 = new zzbj();
        zzbjVar113.zza(R.styleable.AppCompatTheme_viewInflaterClass);
        zzbj = bVarA113.b(zzbjVar113.zzb()).a();
        c.b bVarA114 = c.a("onDeviceDocumentScannerStartLogEvent");
        zzbj zzbjVar114 = new zzbj();
        zzbjVar114.zza(R.styleable.AppCompatTheme_windowActionBar);
        zzbk = bVarA114.b(zzbjVar114.zzb()).a();
        c.b bVarA115 = c.a("onDeviceDocumentScannerFinishLogEvent");
        zzbj zzbjVar115 = new zzbj();
        zzbjVar115.zza(R.styleable.AppCompatTheme_windowActionBarOverlay);
        zzbl = bVarA115.b(zzbjVar115.zzb()).a();
        c.b bVarA116 = c.a("onDeviceDocumentScannerUiStartLogEvent");
        zzbj zzbjVar116 = new zzbj();
        zzbjVar116.zza(R.styleable.AppCompatTheme_windowActionModeOverlay);
        zzbm = bVarA116.b(zzbjVar116.zzb()).a();
        c.b bVarA117 = c.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzbj zzbjVar117 = new zzbj();
        zzbjVar117.zza(R.styleable.AppCompatTheme_windowFixedHeightMajor);
        zzbn = bVarA117.b(zzbjVar117.zzb()).a();
        c.b bVarA118 = c.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzbj zzbjVar118 = new zzbj();
        zzbjVar118.zza(R.styleable.AppCompatTheme_windowFixedHeightMinor);
        zzbo = bVarA118.b(zzbjVar118.zzb()).a();
        c.b bVarA119 = c.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzbj zzbjVar119 = new zzbj();
        zzbjVar119.zza(R.styleable.AppCompatTheme_windowFixedWidthMajor);
        zzbp = bVarA119.b(zzbjVar119.zzb()).a();
        c.b bVarA120 = c.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzbj zzbjVar120 = new zzbj();
        zzbjVar120.zza(R.styleable.AppCompatTheme_windowFixedWidthMinor);
        zzbq = bVarA120.b(zzbjVar120.zzb()).a();
        c.b bVarA121 = c.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzbj zzbjVar121 = new zzbj();
        zzbjVar121.zza(R.styleable.AppCompatTheme_windowMinWidthMajor);
        zzbr = bVarA121.b(zzbjVar121.zzb()).a();
        c.b bVarA122 = c.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzbj zzbjVar122 = new zzbj();
        zzbjVar122.zza(R.styleable.AppCompatTheme_windowMinWidthMinor);
        zzbs = bVarA122.b(zzbjVar122.zzb()).a();
        c.b bVarA123 = c.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzbj zzbjVar123 = new zzbj();
        zzbjVar123.zza(R.styleable.AppCompatTheme_windowNoTitle);
        zzbt = bVarA123.b(zzbjVar123.zzb()).a();
        c.b bVarA124 = c.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzbj zzbjVar124 = new zzbj();
        zzbjVar124.zza(127);
        zzbu = bVarA124.b(zzbjVar124.zzb()).a();
        c.b bVarA125 = c.a("subjectSegmentationOptionalModuleLogEvent");
        zzbj zzbjVar125 = new zzbj();
        zzbjVar125.zza(128);
        zzbv = bVarA125.b(zzbjVar125.zzb()).a();
        c.b bVarA126 = c.a("documentScannerUiModuleScreenViewEvent");
        zzbj zzbjVar126 = new zzbj();
        zzbjVar126.zza(129);
        zzbw = bVarA126.b(zzbjVar126.zzb()).a();
        c.b bVarA127 = c.a("documentScannerUiModuleScreenClickEvent");
        zzbj zzbjVar127 = new zzbj();
        zzbjVar127.zza(130);
        zzbx = bVarA127.b(zzbjVar127.zzb()).a();
        c.b bVarA128 = c.a("documentScannerUiModuleScreenErrorEvent");
        zzbj zzbjVar128 = new zzbj();
        zzbjVar128.zza(131);
        zzby = bVarA128.b(zzbjVar128.zzb()).a();
    }

    private zzha() {
    }

    @Override // ga.d
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zznj zznjVar = (zznj) obj;
        e eVar = (e) obj2;
        eVar.add(zzb, zznjVar.zzf());
        eVar.add(zzc, zznjVar.zzd());
        eVar.add(zzd, (Object) null);
        eVar.add(zze, (Object) null);
        eVar.add(zzf, zznjVar.zze());
        eVar.add(zzg, (Object) null);
        eVar.add(zzh, (Object) null);
        eVar.add(zzi, (Object) null);
        eVar.add(zzj, (Object) null);
        eVar.add(zzk, (Object) null);
        eVar.add(zzl, (Object) null);
        eVar.add(zzm, (Object) null);
        eVar.add(zzn, (Object) null);
        eVar.add(zzo, (Object) null);
        eVar.add(zzp, (Object) null);
        eVar.add(zzq, (Object) null);
        eVar.add(zzr, (Object) null);
        eVar.add(zzs, (Object) null);
        eVar.add(zzt, (Object) null);
        eVar.add(zzu, (Object) null);
        eVar.add(zzv, (Object) null);
        eVar.add(zzw, (Object) null);
        eVar.add(zzx, (Object) null);
        eVar.add(zzy, (Object) null);
        eVar.add(zzz, (Object) null);
        eVar.add(zzA, (Object) null);
        eVar.add(zzB, (Object) null);
        eVar.add(zzC, (Object) null);
        eVar.add(zzD, (Object) null);
        eVar.add(zzE, (Object) null);
        eVar.add(zzF, (Object) null);
        eVar.add(zzG, (Object) null);
        eVar.add(zzH, (Object) null);
        eVar.add(zzI, (Object) null);
        eVar.add(zzJ, (Object) null);
        eVar.add(zzK, (Object) null);
        eVar.add(zzL, (Object) null);
        eVar.add(zzM, (Object) null);
        eVar.add(zzN, zznjVar.zzb());
        eVar.add(zzO, zznjVar.zza());
        eVar.add(zzP, (Object) null);
        eVar.add(zzQ, (Object) null);
        eVar.add(zzR, (Object) null);
        eVar.add(zzS, (Object) null);
        eVar.add(zzT, (Object) null);
        eVar.add(zzU, (Object) null);
        eVar.add(zzV, (Object) null);
        eVar.add(zzW, (Object) null);
        eVar.add(zzX, (Object) null);
        eVar.add(zzY, (Object) null);
        eVar.add(zzZ, (Object) null);
        eVar.add(zzaa, (Object) null);
        eVar.add(zzab, zznjVar.zzc());
        eVar.add(zzac, (Object) null);
        eVar.add(zzad, (Object) null);
        eVar.add(zzae, (Object) null);
        eVar.add(zzaf, (Object) null);
        eVar.add(zzag, (Object) null);
        eVar.add(zzah, (Object) null);
        eVar.add(zzai, (Object) null);
        eVar.add(zzaj, (Object) null);
        eVar.add(zzak, (Object) null);
        eVar.add(zzal, (Object) null);
        eVar.add(zzam, (Object) null);
        eVar.add(zzan, (Object) null);
        eVar.add(zzao, (Object) null);
        eVar.add(zzap, (Object) null);
        eVar.add(zzaq, (Object) null);
        eVar.add(zzar, (Object) null);
        eVar.add(zzas, (Object) null);
        eVar.add(zzat, (Object) null);
        eVar.add(zzau, (Object) null);
        eVar.add(zzav, (Object) null);
        eVar.add(zzaw, (Object) null);
        eVar.add(zzax, (Object) null);
        eVar.add(zzay, (Object) null);
        eVar.add(zzaz, (Object) null);
        eVar.add(zzaA, (Object) null);
        eVar.add(zzaB, (Object) null);
        eVar.add(zzaC, (Object) null);
        eVar.add(zzaD, (Object) null);
        eVar.add(zzaE, (Object) null);
        eVar.add(zzaF, (Object) null);
        eVar.add(zzaG, (Object) null);
        eVar.add(zzaH, (Object) null);
        eVar.add(zzaI, (Object) null);
        eVar.add(zzaJ, (Object) null);
        eVar.add(zzaK, (Object) null);
        eVar.add(zzaL, (Object) null);
        eVar.add(zzaM, (Object) null);
        eVar.add(zzaN, (Object) null);
        eVar.add(zzaO, (Object) null);
        eVar.add(zzaP, (Object) null);
        eVar.add(zzaQ, (Object) null);
        eVar.add(zzaR, (Object) null);
        eVar.add(zzaS, (Object) null);
        eVar.add(zzaT, (Object) null);
        eVar.add(zzaU, (Object) null);
        eVar.add(zzaV, (Object) null);
        eVar.add(zzaW, (Object) null);
        eVar.add(zzaX, (Object) null);
        eVar.add(zzaY, (Object) null);
        eVar.add(zzaZ, (Object) null);
        eVar.add(zzba, (Object) null);
        eVar.add(zzbb, (Object) null);
        eVar.add(zzbc, (Object) null);
        eVar.add(zzbd, (Object) null);
        eVar.add(zzbe, (Object) null);
        eVar.add(zzbf, (Object) null);
        eVar.add(zzbg, (Object) null);
        eVar.add(zzbh, (Object) null);
        eVar.add(zzbi, (Object) null);
        eVar.add(zzbj, (Object) null);
        eVar.add(zzbk, (Object) null);
        eVar.add(zzbl, (Object) null);
        eVar.add(zzbm, (Object) null);
        eVar.add(zzbn, (Object) null);
        eVar.add(zzbo, (Object) null);
        eVar.add(zzbp, (Object) null);
        eVar.add(zzbq, (Object) null);
        eVar.add(zzbr, (Object) null);
        eVar.add(zzbs, (Object) null);
        eVar.add(zzbt, (Object) null);
        eVar.add(zzbu, (Object) null);
        eVar.add(zzbv, (Object) null);
        eVar.add(zzbw, (Object) null);
        eVar.add(zzbx, (Object) null);
        eVar.add(zzby, (Object) null);
    }
}
