package com.google.android.gms.internal.mlkit_vision_document_scanner;

import com.pichillilorenzo.flutter_inappwebview_android.R;
import ga.c;
import ga.d;
import ga.e;

/* JADX INFO: loaded from: classes.dex */
final class zzgi implements d {
    private static final c zzA;
    private static final c zzB;
    private static final c zzC;
    private static final c zzD;
    private static final c zzE;
    private static final c zzF;
    private static final c zzG;
    private static final c zzH;
    private static final c zzI;
    private static final c zzJ;
    private static final c zzK;
    private static final c zzL;
    private static final c zzM;
    private static final c zzN;
    private static final c zzO;
    private static final c zzP;
    private static final c zzQ;
    private static final c zzR;
    private static final c zzS;
    private static final c zzT;
    private static final c zzU;
    private static final c zzV;
    private static final c zzW;
    private static final c zzX;
    private static final c zzY;
    private static final c zzZ;
    static final zzgi zza = new zzgi();
    private static final c zzaA;
    private static final c zzaB;
    private static final c zzaC;
    private static final c zzaD;
    private static final c zzaE;
    private static final c zzaF;
    private static final c zzaG;
    private static final c zzaH;
    private static final c zzaI;
    private static final c zzaJ;
    private static final c zzaK;
    private static final c zzaL;
    private static final c zzaM;
    private static final c zzaN;
    private static final c zzaO;
    private static final c zzaP;
    private static final c zzaQ;
    private static final c zzaR;
    private static final c zzaS;
    private static final c zzaT;
    private static final c zzaU;
    private static final c zzaV;
    private static final c zzaW;
    private static final c zzaX;
    private static final c zzaY;
    private static final c zzaZ;
    private static final c zzaa;
    private static final c zzab;
    private static final c zzac;
    private static final c zzad;
    private static final c zzae;
    private static final c zzaf;
    private static final c zzag;
    private static final c zzah;
    private static final c zzai;
    private static final c zzaj;
    private static final c zzak;
    private static final c zzal;
    private static final c zzam;
    private static final c zzan;
    private static final c zzao;
    private static final c zzap;
    private static final c zzaq;
    private static final c zzar;
    private static final c zzas;
    private static final c zzat;
    private static final c zzau;
    private static final c zzav;
    private static final c zzaw;
    private static final c zzax;
    private static final c zzay;
    private static final c zzaz;
    private static final c zzb;
    private static final c zzba;
    private static final c zzbb;
    private static final c zzbc;
    private static final c zzbd;
    private static final c zzbe;
    private static final c zzbf;
    private static final c zzbg;
    private static final c zzbh;
    private static final c zzbi;
    private static final c zzbj;
    private static final c zzbk;
    private static final c zzbl;
    private static final c zzbm;
    private static final c zzbn;
    private static final c zzbo;
    private static final c zzbp;
    private static final c zzbq;
    private static final c zzbr;
    private static final c zzbs;
    private static final c zzbt;
    private static final c zzbu;
    private static final c zzbv;
    private static final c zzbw;
    private static final c zzbx;
    private static final c zzby;
    private static final c zzc;
    private static final c zzd;
    private static final c zze;
    private static final c zzf;
    private static final c zzg;
    private static final c zzh;
    private static final c zzi;
    private static final c zzj;
    private static final c zzk;
    private static final c zzl;
    private static final c zzm;
    private static final c zzn;
    private static final c zzo;
    private static final c zzp;
    private static final c zzq;
    private static final c zzr;
    private static final c zzs;
    private static final c zzt;
    private static final c zzu;
    private static final c zzv;
    private static final c zzw;
    private static final c zzx;
    private static final c zzy;
    private static final c zzz;

    static {
        c.b bVarA = c.a("systemInfo");
        zzar zzarVar = new zzar();
        zzarVar.zza(1);
        zzb = bVarA.b(zzarVar.zzb()).a();
        c.b bVarA2 = c.a("eventName");
        zzar zzarVar2 = new zzar();
        zzarVar2.zza(2);
        zzc = bVarA2.b(zzarVar2.zzb()).a();
        c.b bVarA3 = c.a("isThickClient");
        zzar zzarVar3 = new zzar();
        zzarVar3.zza(37);
        zzd = bVarA3.b(zzarVar3.zzb()).a();
        c.b bVarA4 = c.a("clientType");
        zzar zzarVar4 = new zzar();
        zzarVar4.zza(61);
        zze = bVarA4.b(zzarVar4.zzb()).a();
        c.b bVarA5 = c.a("modelDownloadLogEvent");
        zzar zzarVar5 = new zzar();
        zzarVar5.zza(3);
        zzf = bVarA5.b(zzarVar5.zzb()).a();
        c.b bVarA6 = c.a("customModelLoadLogEvent");
        zzar zzarVar6 = new zzar();
        zzarVar6.zza(20);
        zzg = bVarA6.b(zzarVar6.zzb()).a();
        c.b bVarA7 = c.a("customModelInferenceLogEvent");
        zzar zzarVar7 = new zzar();
        zzarVar7.zza(4);
        zzh = bVarA7.b(zzarVar7.zzb()).a();
        c.b bVarA8 = c.a("customModelCreateLogEvent");
        zzar zzarVar8 = new zzar();
        zzarVar8.zza(29);
        zzi = bVarA8.b(zzarVar8.zzb()).a();
        c.b bVarA9 = c.a("onDeviceFaceDetectionLogEvent");
        zzar zzarVar9 = new zzar();
        zzarVar9.zza(5);
        zzj = bVarA9.b(zzarVar9.zzb()).a();
        c.b bVarA10 = c.a("onDeviceFaceLoadLogEvent");
        zzar zzarVar10 = new zzar();
        zzarVar10.zza(59);
        zzk = bVarA10.b(zzarVar10.zzb()).a();
        c.b bVarA11 = c.a("onDeviceTextDetectionLogEvent");
        zzar zzarVar11 = new zzar();
        zzarVar11.zza(6);
        zzl = bVarA11.b(zzarVar11.zzb()).a();
        c.b bVarA12 = c.a("onDeviceTextDetectionLoadLogEvent");
        zzar zzarVar12 = new zzar();
        zzarVar12.zza(79);
        zzm = bVarA12.b(zzarVar12.zzb()).a();
        c.b bVarA13 = c.a("onDeviceBarcodeDetectionLogEvent");
        zzar zzarVar13 = new zzar();
        zzarVar13.zza(7);
        zzn = bVarA13.b(zzarVar13.zzb()).a();
        c.b bVarA14 = c.a("onDeviceBarcodeLoadLogEvent");
        zzar zzarVar14 = new zzar();
        zzarVar14.zza(58);
        zzo = bVarA14.b(zzarVar14.zzb()).a();
        c.b bVarA15 = c.a("onDeviceImageLabelCreateLogEvent");
        zzar zzarVar15 = new zzar();
        zzarVar15.zza(48);
        zzp = bVarA15.b(zzarVar15.zzb()).a();
        c.b bVarA16 = c.a("onDeviceImageLabelLoadLogEvent");
        zzar zzarVar16 = new zzar();
        zzarVar16.zza(49);
        zzq = bVarA16.b(zzarVar16.zzb()).a();
        c.b bVarA17 = c.a("onDeviceImageLabelDetectionLogEvent");
        zzar zzarVar17 = new zzar();
        zzarVar17.zza(18);
        zzr = bVarA17.b(zzarVar17.zzb()).a();
        c.b bVarA18 = c.a("onDeviceObjectCreateLogEvent");
        zzar zzarVar18 = new zzar();
        zzarVar18.zza(26);
        zzs = bVarA18.b(zzarVar18.zzb()).a();
        c.b bVarA19 = c.a("onDeviceObjectLoadLogEvent");
        zzar zzarVar19 = new zzar();
        zzarVar19.zza(27);
        zzt = bVarA19.b(zzarVar19.zzb()).a();
        c.b bVarA20 = c.a("onDeviceObjectInferenceLogEvent");
        zzar zzarVar20 = new zzar();
        zzarVar20.zza(28);
        zzu = bVarA20.b(zzarVar20.zzb()).a();
        c.b bVarA21 = c.a("onDevicePoseDetectionLogEvent");
        zzar zzarVar21 = new zzar();
        zzarVar21.zza(44);
        zzv = bVarA21.b(zzarVar21.zzb()).a();
        c.b bVarA22 = c.a("onDeviceSegmentationLogEvent");
        zzar zzarVar22 = new zzar();
        zzarVar22.zza(45);
        zzw = bVarA22.b(zzarVar22.zzb()).a();
        c.b bVarA23 = c.a("onDeviceSmartReplyLogEvent");
        zzar zzarVar23 = new zzar();
        zzarVar23.zza(19);
        zzx = bVarA23.b(zzarVar23.zzb()).a();
        c.b bVarA24 = c.a("onDeviceLanguageIdentificationLogEvent");
        zzar zzarVar24 = new zzar();
        zzarVar24.zza(21);
        zzy = bVarA24.b(zzarVar24.zzb()).a();
        c.b bVarA25 = c.a("onDeviceTranslationLogEvent");
        zzar zzarVar25 = new zzar();
        zzarVar25.zza(22);
        zzz = bVarA25.b(zzarVar25.zzb()).a();
        c.b bVarA26 = c.a("cloudFaceDetectionLogEvent");
        zzar zzarVar26 = new zzar();
        zzarVar26.zza(8);
        zzA = bVarA26.b(zzarVar26.zzb()).a();
        c.b bVarA27 = c.a("cloudCropHintDetectionLogEvent");
        zzar zzarVar27 = new zzar();
        zzarVar27.zza(9);
        zzB = bVarA27.b(zzarVar27.zzb()).a();
        c.b bVarA28 = c.a("cloudDocumentTextDetectionLogEvent");
        zzar zzarVar28 = new zzar();
        zzarVar28.zza(10);
        zzC = bVarA28.b(zzarVar28.zzb()).a();
        c.b bVarA29 = c.a("cloudImagePropertiesDetectionLogEvent");
        zzar zzarVar29 = new zzar();
        zzarVar29.zza(11);
        zzD = bVarA29.b(zzarVar29.zzb()).a();
        c.b bVarA30 = c.a("cloudImageLabelDetectionLogEvent");
        zzar zzarVar30 = new zzar();
        zzarVar30.zza(12);
        zzE = bVarA30.b(zzarVar30.zzb()).a();
        c.b bVarA31 = c.a("cloudLandmarkDetectionLogEvent");
        zzar zzarVar31 = new zzar();
        zzarVar31.zza(13);
        zzF = bVarA31.b(zzarVar31.zzb()).a();
        c.b bVarA32 = c.a("cloudLogoDetectionLogEvent");
        zzar zzarVar32 = new zzar();
        zzarVar32.zza(14);
        zzG = bVarA32.b(zzarVar32.zzb()).a();
        c.b bVarA33 = c.a("cloudSafeSearchDetectionLogEvent");
        zzar zzarVar33 = new zzar();
        zzarVar33.zza(15);
        zzH = bVarA33.b(zzarVar33.zzb()).a();
        c.b bVarA34 = c.a("cloudTextDetectionLogEvent");
        zzar zzarVar34 = new zzar();
        zzarVar34.zza(16);
        zzI = bVarA34.b(zzarVar34.zzb()).a();
        c.b bVarA35 = c.a("cloudWebSearchDetectionLogEvent");
        zzar zzarVar35 = new zzar();
        zzarVar35.zza(17);
        zzJ = bVarA35.b(zzarVar35.zzb()).a();
        c.b bVarA36 = c.a("automlImageLabelingCreateLogEvent");
        zzar zzarVar36 = new zzar();
        zzarVar36.zza(23);
        zzK = bVarA36.b(zzarVar36.zzb()).a();
        c.b bVarA37 = c.a("automlImageLabelingLoadLogEvent");
        zzar zzarVar37 = new zzar();
        zzarVar37.zza(24);
        zzL = bVarA37.b(zzarVar37.zzb()).a();
        c.b bVarA38 = c.a("automlImageLabelingInferenceLogEvent");
        zzar zzarVar38 = new zzar();
        zzarVar38.zza(25);
        zzM = bVarA38.b(zzarVar38.zzb()).a();
        c.b bVarA39 = c.a("isModelDownloadedLogEvent");
        zzar zzarVar39 = new zzar();
        zzarVar39.zza(39);
        zzN = bVarA39.b(zzarVar39.zzb()).a();
        c.b bVarA40 = c.a("deleteModelLogEvent");
        zzar zzarVar40 = new zzar();
        zzarVar40.zza(40);
        zzO = bVarA40.b(zzarVar40.zzb()).a();
        c.b bVarA41 = c.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzar zzarVar41 = new zzar();
        zzarVar41.zza(30);
        zzP = bVarA41.b(zzarVar41.zzb()).a();
        c.b bVarA42 = c.a("aggregatedCustomModelInferenceLogEvent");
        zzar zzarVar42 = new zzar();
        zzarVar42.zza(31);
        zzQ = bVarA42.b(zzarVar42.zzb()).a();
        c.b bVarA43 = c.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzar zzarVar43 = new zzar();
        zzarVar43.zza(32);
        zzR = bVarA43.b(zzarVar43.zzb()).a();
        c.b bVarA44 = c.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzar zzarVar44 = new zzar();
        zzarVar44.zza(33);
        zzS = bVarA44.b(zzarVar44.zzb()).a();
        c.b bVarA45 = c.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzar zzarVar45 = new zzar();
        zzarVar45.zza(34);
        zzT = bVarA45.b(zzarVar45.zzb()).a();
        c.b bVarA46 = c.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzar zzarVar46 = new zzar();
        zzarVar46.zza(35);
        zzU = bVarA46.b(zzarVar46.zzb()).a();
        c.b bVarA47 = c.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzar zzarVar47 = new zzar();
        zzarVar47.zza(36);
        zzV = bVarA47.b(zzarVar47.zzb()).a();
        c.b bVarA48 = c.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzar zzarVar48 = new zzar();
        zzarVar48.zza(46);
        zzW = bVarA48.b(zzarVar48.zzb()).a();
        c.b bVarA49 = c.a("aggregatedOnDeviceSegmentationLogEvent");
        zzar zzarVar49 = new zzar();
        zzarVar49.zza(47);
        zzX = bVarA49.b(zzarVar49.zzb()).a();
        c.b bVarA50 = c.a("pipelineAccelerationInferenceEvents");
        zzar zzarVar50 = new zzar();
        zzarVar50.zza(69);
        zzY = bVarA50.b(zzarVar50.zzb()).a();
        c.b bVarA51 = c.a("remoteConfigLogEvent");
        zzar zzarVar51 = new zzar();
        zzarVar51.zza(42);
        zzZ = bVarA51.b(zzarVar51.zzb()).a();
        c.b bVarA52 = c.a("inputImageConstructionLogEvent");
        zzar zzarVar52 = new zzar();
        zzarVar52.zza(50);
        zzaa = bVarA52.b(zzarVar52.zzb()).a();
        c.b bVarA53 = c.a("leakedHandleEvent");
        zzar zzarVar53 = new zzar();
        zzarVar53.zza(51);
        zzab = bVarA53.b(zzarVar53.zzb()).a();
        c.b bVarA54 = c.a("cameraSourceLogEvent");
        zzar zzarVar54 = new zzar();
        zzarVar54.zza(52);
        zzac = bVarA54.b(zzarVar54.zzb()).a();
        c.b bVarA55 = c.a("imageLabelOptionalModuleLogEvent");
        zzar zzarVar55 = new zzar();
        zzarVar55.zza(53);
        zzad = bVarA55.b(zzarVar55.zzb()).a();
        c.b bVarA56 = c.a("languageIdentificationOptionalModuleLogEvent");
        zzar zzarVar56 = new zzar();
        zzarVar56.zza(54);
        zzae = bVarA56.b(zzarVar56.zzb()).a();
        c.b bVarA57 = c.a("faceDetectionOptionalModuleLogEvent");
        zzar zzarVar57 = new zzar();
        zzarVar57.zza(60);
        zzaf = bVarA57.b(zzarVar57.zzb()).a();
        c.b bVarA58 = c.a("documentDetectionOptionalModuleLogEvent");
        zzar zzarVar58 = new zzar();
        zzarVar58.zza(85);
        zzag = bVarA58.b(zzarVar58.zzb()).a();
        c.b bVarA59 = c.a("documentCroppingOptionalModuleLogEvent");
        zzar zzarVar59 = new zzar();
        zzarVar59.zza(86);
        zzah = bVarA59.b(zzarVar59.zzb()).a();
        c.b bVarA60 = c.a("documentEnhancementOptionalModuleLogEvent");
        zzar zzarVar60 = new zzar();
        zzarVar60.zza(87);
        zzai = bVarA60.b(zzarVar60.zzb()).a();
        c.b bVarA61 = c.a("nlClassifierOptionalModuleLogEvent");
        zzar zzarVar61 = new zzar();
        zzarVar61.zza(55);
        zzaj = bVarA61.b(zzarVar61.zzb()).a();
        c.b bVarA62 = c.a("nlClassifierClientLibraryLogEvent");
        zzar zzarVar62 = new zzar();
        zzarVar62.zza(56);
        zzak = bVarA62.b(zzarVar62.zzb()).a();
        c.b bVarA63 = c.a("accelerationAllowlistLogEvent");
        zzar zzarVar63 = new zzar();
        zzarVar63.zza(57);
        zzal = bVarA63.b(zzarVar63.zzb()).a();
        c.b bVarA64 = c.a("toxicityDetectionCreateEvent");
        zzar zzarVar64 = new zzar();
        zzarVar64.zza(62);
        zzam = bVarA64.b(zzarVar64.zzb()).a();
        c.b bVarA65 = c.a("toxicityDetectionLoadEvent");
        zzar zzarVar65 = new zzar();
        zzarVar65.zza(63);
        zzan = bVarA65.b(zzarVar65.zzb()).a();
        c.b bVarA66 = c.a("toxicityDetectionInferenceEvent");
        zzar zzarVar66 = new zzar();
        zzarVar66.zza(64);
        zzao = bVarA66.b(zzarVar66.zzb()).a();
        c.b bVarA67 = c.a("barcodeDetectionOptionalModuleLogEvent");
        zzar zzarVar67 = new zzar();
        zzarVar67.zza(65);
        zzap = bVarA67.b(zzarVar67.zzb()).a();
        c.b bVarA68 = c.a("customImageLabelOptionalModuleLogEvent");
        zzar zzarVar68 = new zzar();
        zzarVar68.zza(66);
        zzaq = bVarA68.b(zzarVar68.zzb()).a();
        c.b bVarA69 = c.a("codeScannerScanApiEvent");
        zzar zzarVar69 = new zzar();
        zzarVar69.zza(67);
        zzar = bVarA69.b(zzarVar69.zzb()).a();
        c.b bVarA70 = c.a("codeScannerOptionalModuleEvent");
        zzar zzarVar70 = new zzar();
        zzarVar70.zza(68);
        zzas = bVarA70.b(zzarVar70.zzb()).a();
        c.b bVarA71 = c.a("onDeviceExplicitContentCreateLogEvent");
        zzar zzarVar71 = new zzar();
        zzarVar71.zza(70);
        zzat = bVarA71.b(zzarVar71.zzb()).a();
        c.b bVarA72 = c.a("onDeviceExplicitContentLoadLogEvent");
        zzar zzarVar72 = new zzar();
        zzarVar72.zza(71);
        zzau = bVarA72.b(zzarVar72.zzb()).a();
        c.b bVarA73 = c.a("onDeviceExplicitContentInferenceLogEvent");
        zzar zzarVar73 = new zzar();
        zzarVar73.zza(72);
        zzav = bVarA73.b(zzarVar73.zzb()).a();
        c.b bVarA74 = c.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzar zzarVar74 = new zzar();
        zzarVar74.zza(73);
        zzaw = bVarA74.b(zzarVar74.zzb()).a();
        c.b bVarA75 = c.a("onDeviceFaceMeshCreateLogEvent");
        zzar zzarVar75 = new zzar();
        zzarVar75.zza(74);
        zzax = bVarA75.b(zzarVar75.zzb()).a();
        c.b bVarA76 = c.a("onDeviceFaceMeshLoadLogEvent");
        zzar zzarVar76 = new zzar();
        zzarVar76.zza(75);
        zzay = bVarA76.b(zzarVar76.zzb()).a();
        c.b bVarA77 = c.a("onDeviceFaceMeshLogEvent");
        zzar zzarVar77 = new zzar();
        zzarVar77.zza(76);
        zzaz = bVarA77.b(zzarVar77.zzb()).a();
        c.b bVarA78 = c.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzar zzarVar78 = new zzar();
        zzarVar78.zza(77);
        zzaA = bVarA78.b(zzarVar78.zzb()).a();
        c.b bVarA79 = c.a("smartReplyOptionalModuleLogEvent");
        zzar zzarVar79 = new zzar();
        zzarVar79.zza(78);
        zzaB = bVarA79.b(zzarVar79.zzb()).a();
        c.b bVarA80 = c.a("textDetectionOptionalModuleLogEvent");
        zzar zzarVar80 = new zzar();
        zzarVar80.zza(80);
        zzaC = bVarA80.b(zzarVar80.zzb()).a();
        c.b bVarA81 = c.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzar zzarVar81 = new zzar();
        zzarVar81.zza(81);
        zzaD = bVarA81.b(zzarVar81.zzb()).a();
        c.b bVarA82 = c.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzar zzarVar82 = new zzar();
        zzarVar82.zza(82);
        zzaE = bVarA82.b(zzarVar82.zzb()).a();
        c.b bVarA83 = c.a("onDeviceImageQualityAnalysisLogEvent");
        zzar zzarVar83 = new zzar();
        zzarVar83.zza(83);
        zzaF = bVarA83.b(zzarVar83.zzb()).a();
        c.b bVarA84 = c.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzar zzarVar84 = new zzar();
        zzarVar84.zza(84);
        zzaG = bVarA84.b(zzarVar84.zzb()).a();
        c.b bVarA85 = c.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzar zzarVar85 = new zzar();
        zzarVar85.zza(88);
        zzaH = bVarA85.b(zzarVar85.zzb()).a();
        c.b bVarA86 = c.a("imageCaptioningOptionalModuleLogEvent");
        zzar zzarVar86 = new zzar();
        zzarVar86.zza(89);
        zzaI = bVarA86.b(zzarVar86.zzb()).a();
        c.b bVarA87 = c.a("onDeviceImageCaptioningCreateLogEvent");
        zzar zzarVar87 = new zzar();
        zzarVar87.zza(90);
        zzaJ = bVarA87.b(zzarVar87.zzb()).a();
        c.b bVarA88 = c.a("onDeviceImageCaptioningLoadLogEvent");
        zzar zzarVar88 = new zzar();
        zzarVar88.zza(91);
        zzaK = bVarA88.b(zzarVar88.zzb()).a();
        c.b bVarA89 = c.a("onDeviceImageCaptioningInferenceLogEvent");
        zzar zzarVar89 = new zzar();
        zzarVar89.zza(92);
        zzaL = bVarA89.b(zzarVar89.zzb()).a();
        c.b bVarA90 = c.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzar zzarVar90 = new zzar();
        zzarVar90.zza(93);
        zzaM = bVarA90.b(zzarVar90.zzb()).a();
        c.b bVarA91 = c.a("onDeviceDocumentDetectionCreateLogEvent");
        zzar zzarVar91 = new zzar();
        zzarVar91.zza(94);
        zzaN = bVarA91.b(zzarVar91.zzb()).a();
        c.b bVarA92 = c.a("onDeviceDocumentDetectionLoadLogEvent");
        zzar zzarVar92 = new zzar();
        zzarVar92.zza(95);
        zzaO = bVarA92.b(zzarVar92.zzb()).a();
        c.b bVarA93 = c.a("onDeviceDocumentDetectionLogEvent");
        zzar zzarVar93 = new zzar();
        zzarVar93.zza(96);
        zzaP = bVarA93.b(zzarVar93.zzb()).a();
        c.b bVarA94 = c.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzar zzarVar94 = new zzar();
        zzarVar94.zza(97);
        zzaQ = bVarA94.b(zzarVar94.zzb()).a();
        c.b bVarA95 = c.a("onDeviceDocumentCroppingCreateLogEvent");
        zzar zzarVar95 = new zzar();
        zzarVar95.zza(98);
        zzaR = bVarA95.b(zzarVar95.zzb()).a();
        c.b bVarA96 = c.a("onDeviceDocumentCroppingLoadLogEvent");
        zzar zzarVar96 = new zzar();
        zzarVar96.zza(99);
        zzaS = bVarA96.b(zzarVar96.zzb()).a();
        c.b bVarA97 = c.a("onDeviceDocumentCroppingLogEvent");
        zzar zzarVar97 = new zzar();
        zzarVar97.zza(100);
        zzaT = bVarA97.b(zzarVar97.zzb()).a();
        c.b bVarA98 = c.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzar zzarVar98 = new zzar();
        zzarVar98.zza(101);
        zzaU = bVarA98.b(zzarVar98.zzb()).a();
        c.b bVarA99 = c.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzar zzarVar99 = new zzar();
        zzarVar99.zza(R.styleable.AppCompatTheme_textAppearanceLargePopupMenu);
        zzaV = bVarA99.b(zzarVar99.zzb()).a();
        c.b bVarA100 = c.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzar zzarVar100 = new zzar();
        zzarVar100.zza(R.styleable.AppCompatTheme_textAppearanceListItem);
        zzaW = bVarA100.b(zzarVar100.zzb()).a();
        c.b bVarA101 = c.a("onDeviceDocumentEnhancementLogEvent");
        zzar zzarVar101 = new zzar();
        zzarVar101.zza(R.styleable.AppCompatTheme_textAppearanceListItemSecondary);
        zzaX = bVarA101.b(zzarVar101.zzb()).a();
        c.b bVarA102 = c.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzar zzarVar102 = new zzar();
        zzarVar102.zza(R.styleable.AppCompatTheme_textAppearanceListItemSmall);
        zzaY = bVarA102.b(zzarVar102.zzb()).a();
        c.b bVarA103 = c.a("scannerAutoZoomEvent");
        zzar zzarVar103 = new zzar();
        zzarVar103.zza(R.styleable.AppCompatTheme_textAppearancePopupMenuHeader);
        zzaZ = bVarA103.b(zzarVar103.zzb()).a();
        c.b bVarA104 = c.a("lowLightAutoExposureComputationEvent");
        zzar zzarVar104 = new zzar();
        zzarVar104.zza(R.styleable.AppCompatTheme_textAppearanceSearchResultSubtitle);
        zzba = bVarA104.b(zzarVar104.zzb()).a();
        c.b bVarA105 = c.a("lowLightFrameProcessEvent");
        zzar zzarVar105 = new zzar();
        zzarVar105.zza(R.styleable.AppCompatTheme_textAppearanceSearchResultTitle);
        zzbb = bVarA105.b(zzarVar105.zzb()).a();
        c.b bVarA106 = c.a("lowLightSceneDetectionEvent");
        zzar zzarVar106 = new zzar();
        zzarVar106.zza(R.styleable.AppCompatTheme_textAppearanceSmallPopupMenu);
        zzbc = bVarA106.b(zzarVar106.zzb()).a();
        c.b bVarA107 = c.a("onDeviceStainRemovalLogEvent");
        zzar zzarVar107 = new zzar();
        zzarVar107.zza(R.styleable.AppCompatTheme_textColorAlertDialogListItem);
        zzbd = bVarA107.b(zzarVar107.zzb()).a();
        c.b bVarA108 = c.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzar zzarVar108 = new zzar();
        zzarVar108.zza(R.styleable.AppCompatTheme_textColorSearchUrl);
        zzbe = bVarA108.b(zzarVar108.zzb()).a();
        c.b bVarA109 = c.a("stainRemovalOptionalModuleLogEvent");
        zzar zzarVar109 = new zzar();
        zzarVar109.zza(R.styleable.AppCompatTheme_toolbarNavigationButtonStyle);
        zzbf = bVarA109.b(zzarVar109.zzb()).a();
        c.b bVarA110 = c.a("onDeviceShadowRemovalLogEvent");
        zzar zzarVar110 = new zzar();
        zzarVar110.zza(R.styleable.AppCompatTheme_toolbarStyle);
        zzbg = bVarA110.b(zzarVar110.zzb()).a();
        c.b bVarA111 = c.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzar zzarVar111 = new zzar();
        zzarVar111.zza(R.styleable.AppCompatTheme_tooltipForegroundColor);
        zzbh = bVarA111.b(zzarVar111.zzb()).a();
        c.b bVarA112 = c.a("shadowRemovalOptionalModuleLogEvent");
        zzar zzarVar112 = new zzar();
        zzarVar112.zza(R.styleable.AppCompatTheme_tooltipFrameBackground);
        zzbi = bVarA112.b(zzarVar112.zzb()).a();
        c.b bVarA113 = c.a("onDeviceDigitalInkSegmentationLogEvent");
        zzar zzarVar113 = new zzar();
        zzarVar113.zza(R.styleable.AppCompatTheme_viewInflaterClass);
        zzbj = bVarA113.b(zzarVar113.zzb()).a();
        c.b bVarA114 = c.a("onDeviceDocumentScannerStartLogEvent");
        zzar zzarVar114 = new zzar();
        zzarVar114.zza(R.styleable.AppCompatTheme_windowActionBar);
        zzbk = bVarA114.b(zzarVar114.zzb()).a();
        c.b bVarA115 = c.a("onDeviceDocumentScannerFinishLogEvent");
        zzar zzarVar115 = new zzar();
        zzarVar115.zza(R.styleable.AppCompatTheme_windowActionBarOverlay);
        zzbl = bVarA115.b(zzarVar115.zzb()).a();
        c.b bVarA116 = c.a("onDeviceDocumentScannerUiStartLogEvent");
        zzar zzarVar116 = new zzar();
        zzarVar116.zza(R.styleable.AppCompatTheme_windowActionModeOverlay);
        zzbm = bVarA116.b(zzarVar116.zzb()).a();
        c.b bVarA117 = c.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzar zzarVar117 = new zzar();
        zzarVar117.zza(R.styleable.AppCompatTheme_windowFixedHeightMajor);
        zzbn = bVarA117.b(zzarVar117.zzb()).a();
        c.b bVarA118 = c.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzar zzarVar118 = new zzar();
        zzarVar118.zza(R.styleable.AppCompatTheme_windowFixedHeightMinor);
        zzbo = bVarA118.b(zzarVar118.zzb()).a();
        c.b bVarA119 = c.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzar zzarVar119 = new zzar();
        zzarVar119.zza(R.styleable.AppCompatTheme_windowFixedWidthMajor);
        zzbp = bVarA119.b(zzarVar119.zzb()).a();
        c.b bVarA120 = c.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzar zzarVar120 = new zzar();
        zzarVar120.zza(R.styleable.AppCompatTheme_windowFixedWidthMinor);
        zzbq = bVarA120.b(zzarVar120.zzb()).a();
        c.b bVarA121 = c.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzar zzarVar121 = new zzar();
        zzarVar121.zza(R.styleable.AppCompatTheme_windowMinWidthMajor);
        zzbr = bVarA121.b(zzarVar121.zzb()).a();
        c.b bVarA122 = c.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzar zzarVar122 = new zzar();
        zzarVar122.zza(R.styleable.AppCompatTheme_windowMinWidthMinor);
        zzbs = bVarA122.b(zzarVar122.zzb()).a();
        c.b bVarA123 = c.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzar zzarVar123 = new zzar();
        zzarVar123.zza(R.styleable.AppCompatTheme_windowNoTitle);
        zzbt = bVarA123.b(zzarVar123.zzb()).a();
        c.b bVarA124 = c.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzar zzarVar124 = new zzar();
        zzarVar124.zza(127);
        zzbu = bVarA124.b(zzarVar124.zzb()).a();
        c.b bVarA125 = c.a("subjectSegmentationOptionalModuleLogEvent");
        zzar zzarVar125 = new zzar();
        zzarVar125.zza(128);
        zzbv = bVarA125.b(zzarVar125.zzb()).a();
        c.b bVarA126 = c.a("documentScannerUiModuleScreenViewEvent");
        zzar zzarVar126 = new zzar();
        zzarVar126.zza(129);
        zzbw = bVarA126.b(zzarVar126.zzb()).a();
        c.b bVarA127 = c.a("documentScannerUiModuleScreenClickEvent");
        zzar zzarVar127 = new zzar();
        zzarVar127.zza(130);
        zzbx = bVarA127.b(zzarVar127.zzb()).a();
        c.b bVarA128 = c.a("documentScannerUiModuleScreenErrorEvent");
        zzar zzarVar128 = new zzar();
        zzarVar128.zza(131);
        zzby = bVarA128.b(zzarVar128.zzb()).a();
    }

    private zzgi() {
    }

    @Override // ga.d
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzmo zzmoVar = (zzmo) obj;
        e eVar = (e) obj2;
        eVar.add(zzb, zzmoVar.zze());
        eVar.add(zzc, zzmoVar.zza());
        eVar.add(zzd, (Object) null);
        eVar.add(zze, (Object) null);
        eVar.add(zzf, (Object) null);
        eVar.add(zzg, (Object) null);
        eVar.add(zzh, (Object) null);
        eVar.add(zzi, (Object) null);
        eVar.add(zzj, (Object) null);
        eVar.add(zzk, (Object) null);
        eVar.add(zzl, (Object) null);
        eVar.add(zzm, (Object) null);
        eVar.add(zzn, (Object) null);
        eVar.add(zzo, (Object) null);
        eVar.add(zzp, (Object) null);
        eVar.add(zzq, (Object) null);
        eVar.add(zzr, (Object) null);
        eVar.add(zzs, (Object) null);
        eVar.add(zzt, (Object) null);
        eVar.add(zzu, (Object) null);
        eVar.add(zzv, (Object) null);
        eVar.add(zzw, (Object) null);
        eVar.add(zzx, (Object) null);
        eVar.add(zzy, (Object) null);
        eVar.add(zzz, (Object) null);
        eVar.add(zzA, (Object) null);
        eVar.add(zzB, (Object) null);
        eVar.add(zzC, (Object) null);
        eVar.add(zzD, (Object) null);
        eVar.add(zzE, (Object) null);
        eVar.add(zzF, (Object) null);
        eVar.add(zzG, (Object) null);
        eVar.add(zzH, (Object) null);
        eVar.add(zzI, (Object) null);
        eVar.add(zzJ, (Object) null);
        eVar.add(zzK, (Object) null);
        eVar.add(zzL, (Object) null);
        eVar.add(zzM, (Object) null);
        eVar.add(zzN, (Object) null);
        eVar.add(zzO, (Object) null);
        eVar.add(zzP, (Object) null);
        eVar.add(zzQ, (Object) null);
        eVar.add(zzR, (Object) null);
        eVar.add(zzS, (Object) null);
        eVar.add(zzT, (Object) null);
        eVar.add(zzU, (Object) null);
        eVar.add(zzV, (Object) null);
        eVar.add(zzW, (Object) null);
        eVar.add(zzX, (Object) null);
        eVar.add(zzY, (Object) null);
        eVar.add(zzZ, (Object) null);
        eVar.add(zzaa, (Object) null);
        eVar.add(zzab, (Object) null);
        eVar.add(zzac, (Object) null);
        eVar.add(zzad, (Object) null);
        eVar.add(zzae, (Object) null);
        eVar.add(zzaf, (Object) null);
        eVar.add(zzag, (Object) null);
        eVar.add(zzah, (Object) null);
        eVar.add(zzai, (Object) null);
        eVar.add(zzaj, (Object) null);
        eVar.add(zzak, (Object) null);
        eVar.add(zzal, (Object) null);
        eVar.add(zzam, (Object) null);
        eVar.add(zzan, (Object) null);
        eVar.add(zzao, (Object) null);
        eVar.add(zzap, (Object) null);
        eVar.add(zzaq, (Object) null);
        eVar.add(zzar, (Object) null);
        eVar.add(zzas, (Object) null);
        eVar.add(zzat, (Object) null);
        eVar.add(zzau, (Object) null);
        eVar.add(zzav, (Object) null);
        eVar.add(zzaw, (Object) null);
        eVar.add(zzax, (Object) null);
        eVar.add(zzay, (Object) null);
        eVar.add(zzaz, (Object) null);
        eVar.add(zzaA, (Object) null);
        eVar.add(zzaB, (Object) null);
        eVar.add(zzaC, (Object) null);
        eVar.add(zzaD, (Object) null);
        eVar.add(zzaE, (Object) null);
        eVar.add(zzaF, (Object) null);
        eVar.add(zzaG, (Object) null);
        eVar.add(zzaH, (Object) null);
        eVar.add(zzaI, (Object) null);
        eVar.add(zzaJ, (Object) null);
        eVar.add(zzaK, (Object) null);
        eVar.add(zzaL, (Object) null);
        eVar.add(zzaM, (Object) null);
        eVar.add(zzaN, (Object) null);
        eVar.add(zzaO, (Object) null);
        eVar.add(zzaP, (Object) null);
        eVar.add(zzaQ, (Object) null);
        eVar.add(zzaR, (Object) null);
        eVar.add(zzaS, (Object) null);
        eVar.add(zzaT, (Object) null);
        eVar.add(zzaU, (Object) null);
        eVar.add(zzaV, (Object) null);
        eVar.add(zzaW, (Object) null);
        eVar.add(zzaX, (Object) null);
        eVar.add(zzaY, (Object) null);
        eVar.add(zzaZ, (Object) null);
        eVar.add(zzba, (Object) null);
        eVar.add(zzbb, (Object) null);
        eVar.add(zzbc, (Object) null);
        eVar.add(zzbd, (Object) null);
        eVar.add(zzbe, (Object) null);
        eVar.add(zzbf, (Object) null);
        eVar.add(zzbg, (Object) null);
        eVar.add(zzbh, (Object) null);
        eVar.add(zzbi, (Object) null);
        eVar.add(zzbj, (Object) null);
        eVar.add(zzbk, (Object) null);
        eVar.add(zzbl, (Object) null);
        eVar.add(zzbm, zzmoVar.zzd());
        eVar.add(zzbn, zzmoVar.zzc());
        eVar.add(zzbo, (Object) null);
        eVar.add(zzbp, (Object) null);
        eVar.add(zzbq, zzmoVar.zzb());
        eVar.add(zzbr, (Object) null);
        eVar.add(zzbs, (Object) null);
        eVar.add(zzbt, (Object) null);
        eVar.add(zzbu, (Object) null);
        eVar.add(zzbv, (Object) null);
        eVar.add(zzbw, (Object) null);
        eVar.add(zzbx, (Object) null);
        eVar.add(zzby, (Object) null);
    }
}
