package ve;

import md.r;

/* JADX INFO: loaded from: classes2.dex */
public interface a<T> {

    /* JADX INFO: renamed from: ve.a$a, reason: collision with other inner class name */
    public static final class C0467a {
        public static <T> T[] a(a<T> aVar, int i10) {
            throw new r("Generated by Android Extensions automatically");
        }
    }
}
